### ISSUE TITLE
No Options

### ISSUE THREAD

**Issue by AERONIKHD** [crentagon/rbpi_thesis#1]
Hello,
i installed forkpi on my raspberry and its run but i dont have any options.
Should it be so?
![screenshot_1](https://user-images.githubusercontent.com/19529890/27185037-4fa1b8be-51e4-11e7-8864-1645bf391a74.jpg)

**Comment by JCharles210** [comment]
@AERONIKHD how did you get the server up. We keep getting the error "forkpi refused to connect"
